// Common false beliefs Christians carry, paired with a short biblical correction.
// "challenge" is optional — a concrete next step, not just something to read.
const FALSE_BELIEFS = [
  {
    id: 'fb-01',
    belief: "I keep repenting then doing the same thing, God must have had enough of me.",
    explanation: "Christ's love for us is infinite and he is patient. The problem is not sin, but you not focusing on the victory Christ achieved and living from that identity.",
    reference: 'Read Romans 6 and 1 John 1:9',
    challenge: "Confess whatever you're hiding right now, out loud, and thank God for grace before you feel like you've earned it.",
  },
  {
    id: 'fb-02',
    belief: 'God helps those who help themselves.',
    explanation: "This isn't in the Bible — it actually contradicts it. Grace meets you in your weakness and inability, not your self-sufficiency.",
    reference: 'Read Ephesians 2:8-9 and 2 Corinthians 12:9',
  },
  {
    id: 'fb-03',
    belief: 'Money is the root of all evil.',
    explanation: 'The verse never says that. It says the love of money is a root of many kinds of evil — money itself is neutral; what you worship with it is the issue.',
    reference: 'Read 1 Timothy 6:10',
  },
  {
    id: 'fb-04',
    belief: "God won't give you more than you can handle.",
    explanation: "That's a misquote of a verse about resisting temptation, not general suffering. Paul actually wrote that he was crushed beyond his own strength, so he'd rely on God instead of himself.",
    reference: 'Read 1 Corinthians 10:13 and 2 Corinthians 1',
  },
  {
    id: 'fb-05',
    belief: 'Cleanliness is next to godliness.',
    explanation: 'This phrase never appears in the Bible at all — it comes from an old sermon, not Scripture. Godliness is a matter of the heart, not hygiene.',
    reference: 'Read 1 Samuel 16:7 and Matthew 15:11',
  },
  {
    id: 'fb-06',
    belief: "If I have enough faith, I'll never suffer, get sick, or be poor.",
    explanation: 'This "prosperity gospel" idea contradicts the New Testament, which treats suffering as something that refines faith, not something faith prevents.',
    reference: 'Read James 1 and John 16',
    challenge: 'Name one hard season honestly in prayer today, without rushing to find the silver lining.',
  },
  {
    id: 'fb-07',
    belief: 'God is mostly angry and just waiting to punish me.',
    explanation: "God's default posture toward His people isn't wrath, it's steadfast love and patience. Jesus is the exact representation of God's character, and He moved toward sinners, not away from them.",
    reference: 'Read Psalm 103 and Hebrews 1:3',
  },
  {
    id: 'fb-08',
    belief: 'The Old Testament God is different from the New Testament God.',
    explanation: "God's character doesn't change between Testaments — the same mercy that saved Israel is the mercy that sent Jesus. What changes is how fully He's revealed, not who He is.",
    reference: 'Read Malachi 3:6 and Hebrews 13:8',
  },
  {
    id: 'fb-09',
    belief: 'I have to clean myself up before I come to God.',
    explanation: 'You come to God broken, and He does the cleaning up — that\'s the whole point of grace. Trying to fix yourself first skips the part where He meets you as you are.',
    reference: 'Read Romans 5:8 and Matthew 11:28',
    challenge: "Pray honestly right now, before you feel 'ready' or 'clean enough.'",
  },
  {
    id: 'fb-10',
    belief: "Doubting means I have weak faith, or I'm a bad Christian.",
    explanation: 'Doubt honestly brought to God is not the opposite of faith — it\'s often how faith grows. Even Thomas and John the Baptist doubted, and Jesus met them there instead of rejecting them.',
    reference: 'Read John 20 and Jude 1:22',
    challenge: "Tell one trusted person about a doubt you've been hiding.",
  },
  {
    id: 'fb-11',
    belief: "If I were a 'real Christian,' I wouldn't still struggle with this sin.",
    explanation: 'Even Paul described an ongoing internal battle between what he wanted to do and what he actually did. Struggling against sin is evidence you\'re alive to it, not evidence you\'ve failed.',
    reference: 'Read Romans 7 and Galatians 5',
  },
  {
    id: 'fb-12',
    belief: "Once I sin, I have to 'get right' before God will hear my prayers again.",
    explanation: "You don't need to earn your way back into God's hearing — you're invited to come boldly, in the middle of the mess, not after you've cleaned it up.",
    reference: 'Read Hebrews 4:16 and 1 John 1:9',
  },
  {
    id: 'fb-13',
    belief: 'God is disappointed in me.',
    explanation: 'If you belong to Christ, He sees you through the righteousness of Jesus, not your latest failure. Conviction from the Spirit draws you toward Him; shame that says "God is done with you" does not come from Him.',
    reference: 'Read Romans 8:1 and 2 Corinthians 5:21',
  },
  {
    id: 'fb-14',
    belief: 'Following God means my life will be easy and comfortable.',
    explanation: 'Jesus promised the opposite — trouble in this world — while also promising His peace inside of it. Following Him was never sold as a comfort plan.',
    reference: 'Read John 16:33 and 2 Timothy 3:12',
  },
  {
    id: 'fb-15',
    belief: 'I need to earn my salvation through good works.',
    explanation: 'Salvation is a gift you receive, not a wage you earn — good works are the fruit of being saved, not the payment for it.',
    reference: 'Read Ephesians 2:8-9 and Titus 3:5',
  },
  {
    id: 'fb-16',
    belief: "Faith is a feeling — if I don't feel God, I must not really believe.",
    explanation: 'Faith is trust that holds even when feelings are absent, not a constant emotional high. Some of the most faithful people in Scripture cried out feeling completely abandoned.',
    reference: 'Read Psalm 22 and Habakkuk 3:17-18',
    challenge: 'Pray today whether or not you feel anything, and thank Him anyway.',
  },
  {
    id: 'fb-17',
    belief: 'Being a good person is enough to get to heaven.',
    explanation: "Scripture is clear that no one meets God's standard on their own merit — the bar is perfection, and only Christ meets it on your behalf.",
    reference: 'Read Romans 3:23 and John 14:6',
  },
  {
    id: 'fb-18',
    belief: "God can't use me because of my past.",
    explanation: 'God has a long track record of using flawed, broken people — a murderer led Israel, an adulterer wrote most of the Psalms, and a man who denied Jesus three times preached the first sermon of the church.',
    reference: 'Read 2 Corinthians 12:9 and 1 Timothy 1:15-16',
    challenge: 'Share one piece of your story with someone this week, past and all.',
  },
  {
    id: 'fb-19',
    belief: 'Confessing sin is a one-time event, not something I keep bringing to God.',
    explanation: "Confession isn't a single transaction at conversion — it's meant to be an ongoing, honest rhythm with God for the rest of your life.",
    reference: 'Read 1 John 1 and Psalm 51',
    challenge: "Bring today's specific sin to God in prayer right now, by name.",
  },
  {
    id: 'fb-20',
    belief: '"This too shall pass" is in the Bible.',
    explanation: "That phrase never appears in Scripture — it's an old folk proverb. The Bible does promise God's presence through hardship, though, which is worth holding onto instead.",
    reference: 'Read Isaiah 43:2 and 2 Corinthians 4:17',
  },
  {
    id: 'fb-21',
    belief: "Judging is always wrong — the Bible says 'judge not.'",
    explanation: 'That verse warns against hypocritical, self-righteous judgment, not against calling sin what it is. Scripture elsewhere calls believers to judge rightly and gently restore one another.',
    reference: 'Read Matthew 7:1-5 and Galatians 6:1',
    challenge: 'Next time you want to call something out, do it privately and gently, aiming to restore, not shame.',
  },
  {
    id: 'fb-22',
    belief: "Everything happens for a reason, so I shouldn't grieve.",
    explanation: 'God working things for good does not cancel out real sorrow — Jesus himself wept, and Scripture tells believers to mourn with those who mourn.',
    reference: 'Read John 11:35 and Romans 12:15',
    challenge: 'Let yourself actually grieve something today instead of rushing past it.',
  },
  {
    id: 'fb-23',
    belief: "Giving money is how I earn God's blessing or favor.",
    explanation: 'Giving is meant to flow from gratitude for grace already given, not a transaction to purchase more of it. God loves a cheerful giver, not a bargaining one.',
    reference: 'Read 2 Corinthians 9:7 and Ephesians 2:8-9',
    challenge: 'Give something this week purely out of gratitude, expecting nothing back.',
  },
  {
    id: 'fb-24',
    belief: 'If I pray hard enough or have enough faith, God will always answer exactly how I want.',
    explanation: 'Prayer is not a formula that guarantees your specific outcome — even Paul\'s request to remove his "thorn" was answered with "no," and grace instead. God\'s answers are shaped by His will, not just your effort.',
    reference: 'Read 2 Corinthians 12:8-9 and 1 John 5:14',
  },
  {
    id: 'fb-25',
    belief: 'Once you become a Christian, temptation and spiritual struggle stop.',
    explanation: "Becoming a Christian starts a lifelong process of transformation, not an instant finish line — the fight between flesh and Spirit continues, and that's normal, not a sign something's wrong.",
    reference: 'Read Philippians 1:6 and Galatians 5:16-17',
  },
  {
    id: 'fb-26',
    belief: "Maybe God doesn't want me to spread the gospel — that's for other people, not me.",
    explanation: "Jesus didn't give the Great Commission to a special class of Christians — He gave it to all of His followers, and He promised to go with them as they do it.",
    reference: 'Read Matthew 28:18-20',
    challenge: 'This week, share the gospel or your own story with one person, even if it feels awkward.',
  },
];
