// Side quest data: rarities ordered from most common to rarest.
// "oddsN" is the tier's stated "1 in N" chance. For the secret tier,
// each individual quest is 1 in N (not the tier as a whole). Mustard
// Seed isn't rolled directly — it's held to a fixed 45% overall share
// (see MUSTARD_TARGET_SHARE in spin.js), not the raw fallback-of-the-
// other-five-tiers chance its own oddsN/chanceLabel below would imply.
const RARITIES = [
  {
    id: 'mustard-seed',
    name: 'Mustard Seed',
    verse: 'Matthew 17:20',
    chanceLabel: '1 in 2',
    oddsN: 2,
    secret: false,
    soundKey: 'reveal1',
    points: 2,
    color: '#2E7D32',
    colorSoft: '#E8F5E9',
    quests: [
      { id: 'ms-01', text: 'Join a Christian community, pray for someone in need.' },
      { id: 'ms-02', text: 'Hold the door for someone and compliment something about them.' },
      { id: 'ms-03', text: 'Buy water for a homeless person, pray for them.' },
      { id: 'ms-04', text: 'Write 3 Bible verses on paper, leave them at crowded locations.' },
      { id: 'ms-05', text: 'Prepare a meal with God (any kind).' },
      { id: 'ms-06', text: 'Put on worship songs, meditate somewhere quiet.' },
      { id: 'ms-07', text: 'Instead of scrolling, consume something purely positive.' },
      { id: 'ms-08', text: 'Invite God and write your favorite story with Him down together.' },
      { id: 'ms-09', text: 'Do something today that helps you get out of your comfort zone.' },
      { id: 'ms-10', text: 'Tell someone, "I\'m praying for you," and mean it.' },
      { id: 'ms-11', text: 'Coming soon', locked: true },
      { id: 'ms-12', text: 'Coming soon', locked: true },
    ],
  },
  {
    id: 'loaves-and-fishes',
    name: 'Loaves & Fishes',
    verse: 'John 6:9-13',
    chanceLabel: '1 in 5',
    oddsN: 5,
    secret: false,
    soundKey: 'reveal2',
    points: 3,
    color: '#B8860B',
    colorSoft: '#FFF8E1',
    quests: [
      { id: 'lf-01', text: 'Give away a book, clothing, or item someone could use.' },
      { id: 'lf-02', text: 'Invite someone who\'s been struggling to coffee or a walk.' },
      { id: 'lf-03', text: 'Go out to a quiet place and pray for all your loved ones.' },
      { id: 'lf-04', text: 'Sit with someone who is eating alone.' },
      { id: 'lf-05', text: 'Spread the gospel today.' },
      { id: 'lf-06', text: 'Fast (even for a little while) and devote that time to God. Share the gospel with someone today.' },
      { id: 'lf-07', text: 'Donate non-perishable food to someone who might not have it (or a shelter).' },
      { id: 'lf-08', text: 'Make a collection of verses about Jesus\' love for us, and put it somewhere you\'ll remember.' },
      { id: 'lf-09', text: 'Bless everyone you\'d say something negative about, instead.' },
      { id: 'lf-10', text: 'Put all electronics away, walk wherever you want, and talk with God.' },
      { id: 'lf-11', text: 'Coming soon', locked: true },
      { id: 'lf-12', text: 'Coming soon', locked: true },
    ],
  },
  {
    id: 'widows-mite',
    name: "Widow's Mite",
    verse: 'Mark 12:41-44',
    chanceLabel: '1 in 10',
    oddsN: 10,
    secret: false,
    soundKey: 'reveal3',
    points: 5,
    color: '#1565C0',
    colorSoft: '#E3F2FD',
    quests: [
      { id: 'wm-01', text: 'Fast from something you love and pray instead — 1 day.' },
      { id: 'wm-02', text: 'Spend 1 hour volunteering somewhere for free.' },
      { id: 'wm-03', text: 'Do something you\'ve been procrastinating on.' },
      { id: 'wm-04', text: 'Do your chores/help without needing to be told daily.' },
      { id: 'wm-05', text: 'Sincerely apologize to someone you\'ve wronged.' },
      { id: 'wm-06', text: 'Drop a habit for today that you know isn\'t good.' },
      { id: 'wm-07', text: 'Pick something up you\'ve abandoned because it became hard.' },
      { id: 'wm-08', text: 'Initiate small talk with a total stranger.' },
      { id: 'wm-09', text: 'Cook a meal, share a portion with someone.' },
      { id: 'wm-10', text: 'Be kind to someone who is annoying to you today.' },
      { id: 'wm-11', text: 'Coming soon', locked: true },
      { id: 'wm-12', text: 'Coming soon', locked: true },
    ],
  },
  {
    id: 'wilderness-wanderer',
    name: 'Wilderness Wanderer',
    verse: 'Deuteronomy 8:2',
    chanceLabel: '1 in 30',
    oddsN: 30,
    secret: false,
    soundKey: 'reveal4',
    points: 10,
    color: '#D2691E',
    colorSoft: '#FBE9E7',
    quests: [
      { id: 'ww-01', text: 'Try a sport you\'ve been lazy to try.' },
      { id: 'ww-02', text: 'Make a video spreading the gospel, or share it in person.' },
      { id: 'ww-03', text: 'Go through the day giving thanks for everything and don\'t complain.' },
      { id: 'ww-04', text: 'Face a fear you\'ve been avoiding, trusting God with it.' },
      { id: 'ww-05', text: 'Pick up a Godly habit. (Journaling, sports, serving people, etc.)' },
      { id: 'ww-06', text: 'Read 1 Corinthians 12:8-11 and go see which gift you get.' },
      { id: 'ww-07', text: 'Put the people around you first for the day.' },
      { id: 'ww-08', text: 'Give a Bible to someone who doesn\'t have one.' },
      { id: 'ww-09', text: 'Coming soon', locked: true },
      { id: 'ww-10', text: 'Coming soon', locked: true },
      { id: 'ww-11', text: 'Coming soon', locked: true },
      { id: 'ww-12', text: 'Coming soon', locked: true },
    ],
  },
  {
    id: 'refiners-fire',
    name: "Refiner's Fire",
    verse: 'Malachi 3:2-3',
    chanceLabel: '1 in 55',
    oddsN: 55,
    secret: false,
    soundKey: 'reveal5',
    points: 20,
    color: '#C62828',
    colorSoft: '#FFEBEE',
    quests: [
      { id: 'rf-01', text: 'Pick up a hard but good skill, trust God, and don\'t have unrealistic expectations.' },
      { id: 'rf-02', text: 'Attempt something you\'ve wanted to do for a long time but kept telling yourself you\'re not capable of — now persevere through it.' },
      { id: 'rf-03', text: 'Put your full effort into something and love into whatever you do.' },
      { id: 'rf-04', text: 'Take a step towards something God put on your heart, even if you\'re afraid of what people think.' },
      { id: 'rf-05', text: 'Make every effort to serve people today.' },
      { id: 'rf-06', text: 'Spend a full day without your biggest source of entertainment; replace it with music and prayer.' },
      { id: 'rf-07', text: 'Coming soon', locked: true },
      { id: 'rf-08', text: 'Coming soon', locked: true },
      { id: 'rf-09', text: 'Coming soon', locked: true },
      { id: 'rf-10', text: 'Coming soon', locked: true },
      { id: 'rf-11', text: 'Coming soon', locked: true },
      { id: 'rf-12', text: 'Coming soon', locked: true },
    ],
  },
  {
    id: 'burning-bush',
    name: 'Burning Bush',
    verse: 'Exodus 3:2-5',
    chanceLabel: '1 in 110',
    oddsN: 110,
    secret: true,
    soundKey: 'reveal6',
    points: 30,
    color: '#6A1B9A',
    colorSoft: '#F3E5F5',
    quests: [
      { id: 'bb-01', text: 'Give God something you\'ve desperately been trying to control for 2 days, trusting Him and not obsessing over the outcome.' },
      { id: 'bb-02', text: 'Ask God to reveal one area of life where you pick comfort over obedience — and whether or not He reveals it, take a step closer to it.' },
      { id: 'bb-03', text: 'Take something you\'re genuinely talented at, share it with the world, and serve people with it.' },
      { id: 'bb-04', text: 'Put all electronics down for 2 whole days and spend that time building your skills.' },
      { id: 'bb-05', text: 'Coming soon', locked: true },
      { id: 'bb-06', text: 'Coming soon', locked: true },
      { id: 'bb-07', text: 'Coming soon', locked: true },
      { id: 'bb-08', text: 'Coming soon', locked: true },
      { id: 'bb-09', text: 'Coming soon', locked: true },
      { id: 'bb-10', text: 'Coming soon', locked: true },
      { id: 'bb-11', text: 'Coming soon', locked: true },
      { id: 'bb-12', text: 'Coming soon', locked: true },
    ],
  },
];
