// Side quest data: rarities ordered from most common to rarest.
// "oddsN" is the tier's stated "1 in N" chance. For the secret tier,
// each individual quest is 1 in N (not the tier as a whole).
const RARITIES = [
  {
    id: 'mustard-seed',
    name: 'Mustard Seed',
    verse: 'Matthew 17:20',
    chanceLabel: '1 in 2',
    oddsN: 2,
    secret: false,
    soundKey: 'reveal1',
    points: 2,
    color: '#2E7D32',
    colorSoft: '#E8F5E9',
    quests: [
      { id: 'ms-01', text: 'Say a silent prayer of thanks before your next meal.' },
      { id: 'ms-02', text: 'Send an encouraging Bible verse to a friend who needs it.' },
      { id: 'ms-03', text: 'Smile and say "God bless you" to a stranger.' },
      { id: 'ms-04', text: 'Write down three things you\'re grateful for today.' },
      { id: 'ms-05', text: 'Let someone go ahead of you in line, with a kind word.' },
      { id: 'ms-06', text: 'Listen to a worship song and really sit with the lyrics.' },
      { id: 'ms-07', text: 'Text someone "I\'m praying for you" — and mean it.' },
      { id: 'ms-08', text: 'Hold the door and greet the next person warmly.' },
      { id: 'ms-09', text: 'Read one Psalm before bed tonight.' },
      { id: 'ms-10', text: 'Compliment someone on their kindness or effort.' },
      { id: 'ms-11', text: 'Forgive someone in your heart for a small annoyance today.' },
      { id: 'ms-12', text: 'Say a prayer for your city or neighborhood.' },
    ],
  },
  {
    id: 'loaves-and-fishes',
    name: 'Loaves & Fishes',
    verse: 'John 6:9-13',
    chanceLabel: '1 in 7',
    oddsN: 7,
    secret: false,
    soundKey: 'reveal2',
    points: 3,
    color: '#B8860B',
    colorSoft: '#FFF8E1',
    quests: [
      { id: 'lf-01', text: 'Buy a coffee or meal for the person behind you in line.' },
      { id: 'lf-02', text: 'Give away a book, item, or piece of clothing to someone who could use it.' },
      { id: 'lf-03', text: 'Bring a homemade treat to a neighbor.' },
      { id: 'lf-04', text: 'Invite someone who\'s been struggling to coffee or a walk.' },
      { id: 'lf-05', text: 'Share a meal with someone who\'s eating alone.' },
      { id: 'lf-06', text: 'Leave a generous tip with a note that says "God loves you."' },
      { id: 'lf-07', text: 'Donate canned goods or non-perishables to a food pantry.' },
      { id: 'lf-08', text: 'Check in on three people this week, just because.' },
      { id: 'lf-09', text: 'Offer to carry someone\'s groceries or bags.' },
      { id: 'lf-10', text: 'Bake or cook something and share it with a coworker or neighbor.' },
      { id: 'lf-11', text: 'Give up your seat for someone who needs it more.' },
      { id: 'lf-12', text: 'Leave an encouraging note for a stranger to find.' },
    ],
  },
  {
    id: 'widows-mite',
    name: "Widow's Mite",
    verse: 'Mark 12:41-44',
    chanceLabel: '1 in 15',
    oddsN: 15,
    secret: false,
    soundKey: 'reveal3',
    points: 5,
    color: '#1565C0',
    colorSoft: '#E3F2FD',
    quests: [
      { id: 'wm-01', text: 'Give away something that actually costs you — money, time, or a possession you like.' },
      { id: 'wm-02', text: 'Skip a treat this week and give what you saved to someone in need.' },
      { id: 'wm-03', text: 'Spend an hour volunteering where no one will know it was you.' },
      { id: 'wm-04', text: 'Write a heartfelt letter of forgiveness to someone who hurt you.' },
      { id: 'wm-05', text: 'Apologize to someone you\'ve been avoiding making things right with.' },
      { id: 'wm-06', text: 'Give an anonymous gift to someone who is struggling financially.' },
      { id: 'wm-07', text: 'Spend your lunch break sitting with someone who is lonely.' },
      { id: 'wm-08', text: 'Fast from something you love for a full day and pray instead.' },
      { id: 'wm-09', text: 'Give blood, or sign up to donate.' },
      { id: 'wm-10', text: 'Offer to babysit, drive, or help a busy parent for free.' },
      { id: 'wm-11', text: 'Visit someone in a hospital or care home that you don\'t know well.' },
      { id: 'wm-12', text: 'Give someone your full, undivided attention — no phone, no distractions.' },
    ],
  },
  {
    id: 'wilderness-wanderer',
    name: 'Wilderness Wanderer',
    verse: 'Deuteronomy 8:2',
    chanceLabel: '1 in 40',
    oddsN: 40,
    secret: false,
    soundKey: 'reveal4',
    points: 10,
    color: '#D2691E',
    colorSoft: '#FBE9E7',
    quests: [
      { id: 'ww-01', text: 'Walk up to someone experiencing homelessness, sit with them, and ask how you can pray for them.' },
      { id: 'ww-02', text: 'Fast for 24 hours, breaking it in prayer.' },
      { id: 'ww-03', text: 'Share your faith story with someone who has never heard it.' },
      { id: 'ww-04', text: 'Go a full day without complaining about anything, even silently.' },
      { id: 'ww-05', text: 'Reach out and reconcile with someone you\'ve had a falling out with.' },
      { id: 'ww-06', text: 'Volunteer at a shelter or soup kitchen for an afternoon.' },
      { id: 'ww-07', text: 'Pray out loud over your meal in a public restaurant.' },
      { id: 'ww-08', text: 'Spend an hour in total silence and solitude with God — no phone, no distractions.' },
      { id: 'ww-09', text: 'Ask a stranger if there\'s anything you can pray for them about, right there.' },
      { id: 'ww-10', text: 'Give up something you enjoy for a month and donate what you\'d have spent on it.' },
      { id: 'ww-11', text: 'Face a fear you\'ve been avoiding, trusting God through it.' },
      { id: 'ww-12', text: 'Share with someone what God has brought you through.' },
    ],
  },
  {
    id: 'refiners-fire',
    name: "Refiner's Fire",
    verse: 'Malachi 3:2-3',
    chanceLabel: '1 in 70',
    oddsN: 70,
    secret: false,
    soundKey: 'reveal5',
    points: 20,
    color: '#C62828',
    colorSoft: '#FFEBEE',
    quests: [
      { id: 'rf-01', text: 'Share your faith with someone you know disagrees with you, in love and respect.' },
      { id: 'rf-02', text: 'Forgive someone face-to-face for something serious, out loud.' },
      { id: 'rf-03', text: 'Stand up for someone being mocked or mistreated, even if it costs you socially.' },
      { id: 'rf-04', text: 'Ask forgiveness in person from someone you deeply wronged.' },
      { id: 'rf-05', text: 'Give away something significant — a large sum or a prized possession — without telling anyone.' },
      { id: 'rf-06', text: 'Spend three days fasting and praying over one specific need.' },
      { id: 'rf-07', text: 'Share the Gospel with a total stranger.' },
      { id: 'rf-08', text: 'Reconcile a broken relationship that\'s been unresolved for years.' },
      { id: 'rf-09', text: 'Go a full week without entertainment and devote that time to prayer and Scripture.' },
      { id: 'rf-10', text: 'Serve someone who has wronged you, without being asked and without recognition.' },
      { id: 'rf-11', text: 'Speak truth in love about something hard, even if it risks the relationship.' },
      { id: 'rf-12', text: 'Spend a night in prayer, interceding for someone specific by name.' },
    ],
  },
  {
    id: 'burning-bush',
    name: 'Burning Bush',
    verse: 'Exodus 3:2-5',
    chanceLabel: '1 in 125',
    oddsN: 125,
    secret: true,
    soundKey: 'reveal6',
    points: 30,
    color: '#6A1B9A',
    colorSoft: '#F3E5F5',
    quests: [
      { id: 'bb-01', text: 'Fast and pray for three full days seeking God\'s direction on a major decision — then act on it.' },
      { id: 'bb-02', text: 'Step fully out of your comfort zone: commit to a mission trip, local or abroad, and actually book it.' },
    ],
  },
];
